# File: docker-compose.yml
version: "3.8"
services:

    # 1. LAYANAN APLIKASI (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-pertanian
        container_name: pertanian-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            # Variabel akan diambil dari file .env
            DB_CONNECTION: mysql
            DB_HOST: ${DB_HOST}   # Host MariaDB eksternal
            DB_PORT: ${DB_PORT:-3306}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        # Hapus 'depends_on: db' karena DB ada di luar Docker Compose

    # 2. LAYANAN WEB SERVER (NGINX)
    nginx:
        image: nginx:alpine
        container_name: pertanian-nginx
        restart: unless-stopped
        ports:
            - "8083:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    # HAPUS LAYANAN 'db' (MariaDB)